title: Jacob Simon Areickal
description: I am currently working as a Java developer. A very passionate engineer interested in machine learning and artificial intelligence. 
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
