title: <p align="center"> Jacob Simon Areickal </p>
logo: assets/images/jacob.jpeg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/jacob-simon-areickal">LinkedIn</a> |
  <a href="https://github.com/jacobsimonareickal">GitHub</a>
 
  <br>   
  I am currently working as Java develeoper in insurance domain. I am very passionate about Artificial intelligence and Machine Learning.
  <br>
  </p> 
theme: jekyll-theme-architect
